# Default configuration
[default.databases.tanjun]
url = "tanjun.sqlite"

# Debug configuration
[debug.jwt]
secret = "jwt.secret.debug"

# Test configuration
[test.jwt]
secret = "jwt.secret.test"

[test.databases.tanjun]
url = "tanjun-test.sqlite"
