# Default configuration
[default.databases.tanjun]
url = "tanjun.sqlite"

[default.jwt]
duration_seconds = 600

# Debug configuration
[debug.jwt]
secret = "jwt.secret.debug"

# Test configuration
[test.jwt]
secret = "jwt.secret.test"

[test.databases.tanjun]
url = "tanjun-test.sqlite"
