# Default configuration
[default.databases.tanjun]
url = "data/tanjun.sqlite"

[default]
jwt_duration_seconds = 600

# Debug configuration
[debug]
jwt_secret = "jwt.secret.debug"

# Test configuration
[test]
jwt_secret = "jwt.secret.test"

[test.databases.tanjun]
url = "data/tanjun-test.sqlite"
